import { randomBytes } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse as parseEnvFileContents } from "dotenv";
import { logger } from "./middleware/logger.js";
import { resolvePaperclipEnvPath } from "./paths.js";

const AGENT_JWT_SECRET_ENV_KEY = "PAPERCLIP_AGENT_JWT_SECRET";

type LocalTrustedAgentJwtBootstrapStatus =
  | "already_configured"
  | "using_better_auth_secret"
  | "loaded_from_env_file"
  | "created_env_file";

export interface LocalTrustedAgentJwtBootstrapResult {
  status: LocalTrustedAgentJwtBootstrapStatus;
  envPath: string | null;
}

function nonEmpty(value: string | undefined): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function renderEnvFile(key: string, value: string): string {
  return [
    "# Paperclip environment variables",
    "# Generated by the Paperclip server",
    `${key}=${formatEnvValue(value)}`,
    "",
  ].join("\n");
}

function readAgentJwtSecretFromEnvFile(filePath: string): string | null {
  if (!existsSync(filePath)) return null;
  const parsed = parseEnvFileContents(readFileSync(filePath, "utf8"));
  return nonEmpty(parsed[AGENT_JWT_SECRET_ENV_KEY]);
}

function writeAgentJwtSecretToEnvFile(filePath: string, secret: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true });

  if (!existsSync(filePath)) {
    writeFileSync(filePath, renderEnvFile(AGENT_JWT_SECRET_ENV_KEY, secret), { mode: 0o600 });
    return;
  }

  const prefix = readFileSync(filePath, "utf8").endsWith("\n") ? "" : "\n";
  appendFileSync(filePath, `${prefix}${AGENT_JWT_SECRET_ENV_KEY}=${formatEnvValue(secret)}\n`);
}

export function ensureLocalTrustedAgentJwtSecret(): LocalTrustedAgentJwtBootstrapResult {
  if (nonEmpty(process.env.PAPERCLIP_AGENT_JWT_SECRET)) {
    return { status: "already_configured", envPath: null };
  }

  if (nonEmpty(process.env.BETTER_AUTH_SECRET)) {
    return { status: "using_better_auth_secret", envPath: null };
  }

  const envPath = resolvePaperclipEnvPath();
  const fileSecret = readAgentJwtSecretFromEnvFile(envPath);
  if (fileSecret) {
    process.env.PAPERCLIP_AGENT_JWT_SECRET = fileSecret;
    return { status: "loaded_from_env_file", envPath };
  }

  const secret = randomBytes(32).toString("hex");
  writeAgentJwtSecretToEnvFile(envPath, secret);
  process.env.PAPERCLIP_AGENT_JWT_SECRET = secret;
  logger.info({ envPath }, "Generated PAPERCLIP_AGENT_JWT_SECRET for local_trusted startup");
  return { status: "created_env_file", envPath };
}
